################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: false

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: n8nthai-network
    swarmMode: false
  file:
    directory: "/etc/traefik/config"
    watch: true

################################################################
# Entry points configuration
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

################################################################
# Let's Encrypt configuration
################################################################
certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@example.com"  # Replace with your email
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web

################################################################
# Logging configuration
################################################################
log:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

################################################################
# Metrics configuration (optional)
################################################################
metrics:
  prometheus:
    entryPoint: traefik
    addEntryPointsLabels: true
    addServicesLabels: true
